version: '3.7'

services:
  traefik:
    image: traefik:1.7-alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:traefik.tripleperformance.fr'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./engine/traefik/traefik-prod.toml:/etc/traefik/traefik.toml
      - ./.data/acme.json:/etc/traefik/acme.json

  web:
    image: ghcr.io/neayi/tripleperformance/wiki:$WIKI_VERSION_PROD
    ## Uncomment in order to build the image on the current host
    #build:
    #  context: .
    #  dockerfile: engine/php_server/Dockerfile
    #  target: prod_sources
    #  args:
    #    - MSMTP_SECRET=$MSMTP_SECRET
    restart: always
    env_file: .env
    volumes:
      - ./.data/images:/var/www/html/images
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:wiki.tripleperformance.fr, tripleperformance.fr, pratiques.tripleperformance.fr, www.tripleperformance.fr, 3perf.fr, de.tripleperformance.ag, en.tripleperformance.ag, es.tripleperformance.ag, fr.tripleperformance.ag, it.tripleperformance.ag, nl.tripleperformance.ag, pl.tripleperformance.ag'
      - 'traefik.frontend.redirect.regex=^https?://(pratiques.)?tripleperformance.fr/(.*)'
      - 'traefik.frontend.redirect.replacement=https://wiki.tripleperformance.fr/$${2}'
      - 'traefik.frontend.redirect.permanent=true'
    networks:
      default:
        aliases:
          - wiki.tripleperformance.fr
          - de.tripleperformance.ag
          - en.tripleperformance.ag
          - es.tripleperformance.ag
          - fr.tripleperformance.ag
          - it.tripleperformance.ag
          - nl.tripleperformance.ag
          - pl.tripleperformance.ag

  insights:
    image: ghcr.io/neayi/insights/insights:$INSIGHTS_VERSION_PROD
    env_file: insights/.env
    ## Uncomment in order to build the image on the current host
    #build:
    #  context: insights
    #  dockerfile: dockerfiles/php/Dockerfile
    #  target: prod_sources
    restart: always
    networks:
      - default
      - traefik
    volumes:
      - ./.data/insights_prod_storage:/var/www/html/storage/app/public
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:insights.tripleperformance.fr'

  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file: .env
    volumes:
      - ./.data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:phpmyadmin.tripleperformance.fr'

  redis:
    image: redis
    restart: always

  elasticsearch:
    image: elasticsearch:6.8.23
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: "true"
      http.cors.enabled: "true"
      http.cors.allow-origin: "https://elasticvue.tripleperformance.fr"
      http.cors.allow-headers: X-Requested-With,Content-Type,Content-Length,Authorization
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./.data/elasticsearch:/usr/share/elasticsearch/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=9200'
      - 'traefik.frontend.rule=Host:elasticsearch.tripleperformance.fr'

  elasticvue:
    image: cars10/elasticvue
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:elasticvue.tripleperformance.fr'

  parsoid:
    image: thenets/parsoid:0.11
    restart: always
    environment:
      PARSOID_DOMAIN_prod: http://wiki.tripleperformance.fr/api.php
      PARSOID_DOMAIN_FR_prod: http://fr.tripleperformance.ag/api.php
      PARSOID_DOMAIN_ES_prod: http://es.tripleperformance.ag/api.php
      PARSOID_DOMAIN_FI_prod: http://fi.tripleperformance.ag/api.php
      PARSOID_DOMAIN_PT_prod: http://pt.tripleperformance.ag/api.php
      PARSOID_DOMAIN_IT_prod: http://it.tripleperformance.ag/api.php
      PARSOID_DOMAIN_GR_prod: http://gr.tripleperformance.ag/api.php
      PARSOID_DOMAIN_HU_prod: http://hu.tripleperformance.ag/api.php
      PARSOID_DOMAIN_DE_prod: http://de.tripleperformance.ag/api.php
      PARSOID_DOMAIN_EN_prod: http://en.tripleperformance.ag/api.php
      PARSOID_DOMAIN_PO_prod: http://po.tripleperformance.ag/api.php
      PARSOID_DOMAIN_NL_prod: http://nl.tripleperformance.ag/api.php
      PARSOID_DOMAIN_preprod: http://wiki.preprod.tripleperformance.fr/api.php
      PARSOID_DOMAIN_FR_preprod: http://fr.preprod.tripleperformance.ag/api.php
      PARSOID_DOMAIN_ES_preprod: http://es.preprod.tripleperformance.ag/api.php
      PARSOID_DOMAIN_FI_preprod: http://fi.preprod.tripleperformance.ag/api.php
      PARSOID_DOMAIN_PT_preprod: http://pt.preprod.tripleperformance.ag/api.php
      PARSOID_DOMAIN_IT_preprod: http://it.preprod.tripleperformance.ag/api.php
      PARSOID_DOMAIN_GR_preprod: http://gr.preprod.tripleperformance.ag/api.php
      PARSOID_DOMAIN_HU_preprod: http://hu.preprod.tripleperformance.ag/api.php
      PARSOID_DOMAIN_DE_preprod: http://de.preprod.tripleperformance.ag/api.php
      PARSOID_DOMAIN_EN_preprod: http://en.preprod.tripleperformance.ag/api.php
      PARSOID_DOMAIN_PO_preprod: http://po.preprod.tripleperformance.ag/api.php
      PARSOID_DOMAIN_NL_preprod: http://nl.preprod.tripleperformance.ag/api.php
    links:
      - web:wiki.tripleperformance.fr
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=8000'
      - 'traefik.frontend.rule=Host:parsoid.tripleperformance.fr'

  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./piwigo/config:/config
      - ./piwigo/gallery:/gallery
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:photos.tripleperformance.fr'

networks:
  default: ~
  traefik:
    name: tripleperformance_traefik
